**INTEGRANTES**

Nome completo: Alexsandro dos Santos Silva - RA: 319200068

Nome completo: Evelyn Castro Maia e Souza - RA: 3019200390

Nome completo: Filipe Queiroz de Abreu - RA: 919210778

Nome completo: Kaike Soares Silva - RA: 919209611

Nome completo: Nailda Rodrigues Gonçalves - RA: 919203559

## **ATIVIDADE 1**

In [1]:
#IMPORTANDO A BIBLIOTECA
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
#from sklearn.preprocessing import OneHotEncoder

In [2]:
#LENDO OS ARQUIVOS
df1 = pd.read_csv('reclamacoes-fundamentadas-sindec-2012.csv', nrows=1000)
df2 = pd.read_csv('reclamacoes-fundamentadas-sindec-2013.csv', nrows=1000)
df3 = pd.read_csv('reclamacoes-fundamentadas-sindec-2014.csv', nrows=1000)
df4 = pd.read_csv('reclamacoes-fundamentadas-sindec-2015.csv', nrows=1000)
df5 = pd.read_csv('reclamacoes-fundamentadas-sindec-2016.csv', nrows=1000)

In [3]:
#NOME DOS CONJUNTOS DE DADOS
frame = [df1, df2, df3, df4, df5]

In [4]:
#CONCATENA OS DATASETS
df = pd.concat(frame)

In [5]:
df

,AnoCalendario,DataArquivamento,DataAbertura,CodigoRegiao,Regiao,UF,strRazaoSocial,strNomeFantasia,Tipo,NumeroCNPJ,...,CNAEPrincipal,DescCNAEPrincipal,Atendida,CodigoAssunto,DescricaoAssunto,CodigoProblema,DescricaoProblema,SexoConsumidor,FaixaEtariaConsumidor,CEPConsumidor
0,2012,2012-07-13 17:44:45.000,2009-09-17 10:48:42.000,3,Sudeste,ES,IBI PROMOTORA DE VENDAS LTDA.,IBI CARD,1,7.448120e+13,...,7490104.0,ATIVIDADES DE INTERMEDIAÇÃO E AGENCIAMENTO DE ...,N,54,Cartão de Crédito,32,Calculo de prestação em atraso,F,mais de 70 anos,29072040
1,2012,2012-07-13 17:37:19.000,2009-09-17 10:02:24.000,3,Sudeste,ES,SAMSUNG ELETRONICA DA AMAZONIA LTDA,SAMSUNG,1,2.802730e+11,...,2640000.0,"FABRICAÇÃO DE APARELHOS DE RECEPÇÃO, REPRODUÇÃ...",N,101,"Telefone ( Convencional, Celular, Interfone, E...",102,"Garantia (Abrangência, cobertura, etc.)",M,entre 31 a 40 anos,29115360
2,2012,2012-07-16 09:07:13.000,2009-09-17 11:36:47.000,3,Sudeste,ES,LINNU''S AUTOMOVEIS LTDA.,LINNUS AUTOMOVEIS,1,3.635548e+13,...,4512902.0,COMÉRCIO SOB CONSIGNAÇÃO DE VEÍCULOS AUTOMOTORES,N,129,Carro Nacional Zero ( Montadora ),111,Venda enganosa,M,entre 21 a 30 anos,29060110
3,2012,2012-12-10 09:05:09.000,2009-09-21 09:01:49.000,5,Centro-oeste,GO,AMAZON PC INDUSTRIA E COMERCIO DE MICROCOMPUTA...,AMAZON PC,1,1.614079e+12,...,2621300.0,FABRICAÇÃO DE EQUIPAMENTOS DE INFORMÁTICA,S,102,Microcomputador / Produtos de Informática,102,"Garantia (Abrangência, cobertura, etc.)",M,entre 21 a 30 anos,75911000
4,2012,2012-07-13 17:51:01.000,2009-09-18 17:32:22.000,3,Sudeste,ES,OFFICINA REVESTIMENTOS LTDA ME,NaN,1,5.444155e+12,...,4744005.0,COMÉRCIO VAREJISTA DE MATERIAIS DE CONSTRUÇÃO ...,N,118,Material de Acabamento de Construção Pronto (P...,116,"Contrato/pedido/orçamento (rescisão, descumpri...",M,Nao Informada,29090120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2016,2016-08-19 10:25:26.000,2015-04-14 09:25:52.000,2,Nordeste,BA,ESAU BARBOSA CARDOSO,REFRIGERAÇÃO ENXUTA,1,1.469089e+13,...,9521500.0,REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS ELETROE...,N,92,Máquina de Lavar Roupa / Louça e Secadora,105,Produto com vício,F,entre 21 a 30 anos,41270330.0
996,2016,2016-05-13 12:04:18.000,2014-09-22 07:43:28.000,2,Nordeste,BA,ESAU BARBOSA CARDOSO,REFRIGERAÇÃO ENXUTA,1,1.469089e+13,...,9521500.0,REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS ELETROE...,S,288,Máquinas e Equipamentos,113,Falta de peça de reposição,M,entre 51 a 60 anos,41611070.0
997,2016,2016-05-12 17:44:42.000,2013-08-21 09:53:00.000,2,Nordeste,BA,SALVATUR-SALVADOR TURISMO LTDA,BAHIA TRAVEL OPERADORA,1,1.469395e+13,...,7911200.0,AGÊNCIAS DE VIAGENS,N,157,"Transporte ( Rodoviário, Passageiros, Cargas, ...",134,Cobrança indevida/abusiva,M,entre 41 a 50 anos,41253330.0
998,2016,2016-05-06 10:36:09.000,2016-03-16 17:44:37.000,4,Sul,PR,E-POINT COMERCIO DE ELETRÔNICOS E ACESSORIOS E...,MY MOB,1,1.470342e+13,...,4752100.0,COMÉRCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENT...,S,101,"Telefone ( Convencional, Celular, Interfone, E...",105,Produto com vício,F,entre 31 a 40 anos,83430000.0
999,2016,2016-12-02 11:19:54.000,2013-04-15 17:22:56.000,2,Nordeste,BA,RICARDO JEFFERSON DOS SANTOS,AMIGOS ELETRO,1,1.472729e+13,...,4713001.0,LOJAS DE DEPARTAMENTOS OU MAGAZINES,N,102,Microcomputador / Produtos de Informática,107,Não entrega/demora na entrega do produto,M,entre 41 a 50 anos,40310770.0

## **ATIVIDADE 2**

Exploração do dataset full gerado na entrega 1 de agosto. 
Usar os recursos de mineração de textos no dataset e demais recursos de exploração do dataset. 

*** Utilizar o mesmo colab usado na entrega 1, apenas dar continuidade.

In [6]:
print(df.columns)

Index(['AnoCalendario', 'DataArquivamento', 'DataAbertura', 'CodigoRegiao',
       'Regiao', 'UF', 'strRazaoSocial', 'strNomeFantasia', 'Tipo',
       'NumeroCNPJ', 'RadicalCNPJ', 'RazaoSocialRFB', 'NomeFantasiaRFB',
       'CNAEPrincipal', 'DescCNAEPrincipal', 'Atendida', 'CodigoAssunto',
       'DescricaoAssunto', 'CodigoProblema', 'DescricaoProblema',
       'SexoConsumidor', 'FaixaEtariaConsumidor', 'CEPConsumidor'],
      dtype='object')

In [7]:
#INFORMAÇÕES DE ESTATÍSTICA DESCRITIVAS, COMO: MÉDIA, DESVIO PADRÃO, MÁXIMO, MÍNIMO E OUTRAS TENDÊNCIAS CENTRAIS
df.describe().astype(int)

,AnoCalendario,CodigoRegiao,Tipo,NumeroCNPJ,RadicalCNPJ,CNAEPrincipal,CodigoAssunto,CodigoProblema
count,5000,5000,5000,4385,4358,4269,5000,5000
mean,2014,2,0,-2147483648,58715463,5424767,131,114
std,1,1,0,-2147483648,1524038626,1620375,67,54
min,2012,1,0,191,0,159802,2,3
25%,2013,2,1,-2147483648,2449992,4652400,93,102
50%,2014,2,1,-2147483648,7984491,6110801,102,105
75%,2015,3,1,-2147483648,33041260,6422100,186,134
max,2016,5,1,-2147483648,-2147483648,9609299,288,262

In [8]:
df.info()
#Verificando os tipos de dados

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   AnoCalendario          5000 non-null   int64
 1   DataArquivamento       5000 non-null   object
 2   DataAbertura           5000 non-null   object
 3   CodigoRegiao           5000 non-null   int64
 4   Regiao                 5000 non-null   object
 5   UF                     5000 non-null   object
 6   strRazaoSocial         5000 non-null   object
 7   strNomeFantasia        4205 non-null   object
 8   Tipo                   5000 non-null   int64
 9   NumeroCNPJ             4385 non-null   float64
 10  RadicalCNPJ            4358 non-null   float64
 11  RazaoSocialRFB         4279 non-null   object
 12  NomeFantasiaRFB        2161 non-null   object
 13  CNAEPrincipal          4269 non-null   float64
 14  DescCNAEPrincipal      4236 non-null   object
 15  Atendida               5000 non-null   object
 16  CodigoAssunto          5000 non-null   int64
 17  DescricaoAssunto       5000 non-null   object
 18  CodigoProblema         5000 non-null   int64
 19  DescricaoProblema      5000 non-null   object
 20  SexoConsumidor         5000 non-null   object
 21  FaixaEtariaConsumidor  5000 non-null   object
 22  CEPConsumidor          4600 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 937.5+ KB

In [9]:
df.isnull().sum().sort_values(ascending = False)
#verificando valores nulos

NomeFantasiaRFB          2839
strNomeFantasia           795
DescCNAEPrincipal         764
CNAEPrincipal             731
RazaoSocialRFB            721
RadicalCNPJ               642
NumeroCNPJ                615
CEPConsumidor             400
Tipo                        0
strRazaoSocial              0
UF                          0
DataArquivamento            0
Regiao                      0
CodigoRegiao                0
DataAbertura                0
Atendida                    0
CodigoAssunto               0
DescricaoAssunto            0
CodigoProblema              0
DescricaoProblema           0
SexoConsumidor              0
FaixaEtariaConsumidor       0
AnoCalendario               0
dtype: int64

In [10]:
#Verificando a porcentage de dados faltante por coluna
percent_missing = df.isna().sum() * 100 / len(df)
percent_missing_df = pd.DataFrame({'Percent Missing': percent_missing})
percent_missing_df.sort_values(['Percent Missing'], ascending=False)

                       Percent Missing
NomeFantasiaRFB                  56.78
strNomeFantasia                  15.90
DescCNAEPrincipal                15.28
CNAEPrincipal                    14.62
RazaoSocialRFB                   14.42
RadicalCNPJ                      12.84
NumeroCNPJ                       12.30
CEPConsumidor                     8.00
Tipo                              0.00
strRazaoSocial                    0.00
UF                                0.00
DataArquivamento                  0.00
Regiao                            0.00
CodigoRegiao                      0.00
DataAbertura                      0.00
Atendida                          0.00
CodigoAssunto                     0.00
DescricaoAssunto                  0.00
CodigoProblema                    0.00
DescricaoProblema                 0.00
SexoConsumidor                    0.00
FaixaEtariaConsumidor             0.00
AnoCalendario                     0.00

In [11]:
#derrubando coluna com mais da metade dos dados faltantes
df = df.drop(columns = 'NomeFantasiaRFB')

In [12]:
#FAIXAS ETARIAS DOS CONSUMIDORES
serviceGroups = df['FaixaEtariaConsumidor']
serviceGroups.value_counts().sort_index()

Nao Informada          354
Nao se aplica            1
até 20 anos             84
entre 21 a 30 anos     871
entre 31 a 40 anos    1188
entre 41 a 50 anos    1028
entre 51 a 60 anos     760
entre 61 a 70 anos     495
mais de 70 anos        219
Name: FaixaEtariaConsumidor, dtype: int64

In [18]:
grupoSexo = df.groupby('SexoConsumidor')
grupoSexo.value_counts()

SexoConsumidor  AnoCalendario  DataArquivamento         DataAbertura             CodigoRegiao  Regiao        UF  strRazaoSocial                                         strNomeFantasia                         Tipo  NumeroCNPJ    RadicalCNPJ  RazaoSocialRFB                                                       CNAEPrincipal  DescCNAEPrincipal                                                                                       Atendida  CodigoAssunto  DescricaoAssunto                                                                   CodigoProblema  DescricaoProblema                                                                                              FaixaEtariaConsumidor  CEPConsumidor
F               2012           2012-01-02 10:15:57.000  2011-10-20 14:42:46.000  5             Centro-oeste  GO  LG                                                     LG                                      1     1.166372e+12  1166372.0    LG ELECTRONICS DO BRASIL LTDA                                        2622100.0      FABRICAÇÃO DE PERIFÉRICOS PARA EQUIPAMENTOS DE INFORMÁTICA                                              S         96             Televisão / Vídeo Cassete / Filmadora / Video-Laser                                102             Garantia (Abrangência, cobertura, etc.)                                                                        Nao Informada          72855009         1
                2016           2016-10-20 14:53:45.000  2016-08-18 14:11:33.000  4             Sul           SC  ACTION & PRICE LTDA                                    ACTIVA PRODUCOES E EVENTOS              1     1.068315e+12  1068315.0    ACTION & PRICE LTDA                                                  8230001.0      SERVIÇOS DE ORGANIZAÇÃO DE FEIRAS, CONGRESSOS, EXPOSIÇÕES E FESTAS                                      S         246            Eventos ( Festas, Buffet, Formatura, Etc. )                                        251             SAC - Acesso ao serviço (onerosidade, problemas no menu, indisponibilidade, inacessibilidade aos deficientes)  entre 21 a 30 anos     88140000.0       1
                               2016-11-11 09:22:00.000  2016-06-08 09:36:13.000  2             Nordeste      PB  COMPANHIA DE ÁGUA E ESGOTOS DA PARAÍBA                 CAGEPA                                  1     9.123654e+12  9123654.0    COMPANHIA DE AGUA E ESGOTOS DA PARAIBA CAGEPA                        3600601.0      CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO DE ÁGUA                                                             S         183            Água / Esgoto                                                                      134             Cobrança indevida/abusiva                                                                                      mais de 70 anos        58080050.0       1
                               2016-11-11 17:08:52.000  2016-09-29 08:18:26.000  2             Nordeste      MA  ICEP INST. DE CAPAC. E ENS. PROFISSIONALIZANTE         GOLD ICEP                               1     3.542793e+12  3542793.0    ICEP-INSTITUTO DE CAPACITACAO E ENSINO PROFISSIONALIZANTE LTDA - ME  8541400.0      EDUCAÇÃO PROFISSIONAL DE NÍVEL TÉCNICO                                                                  N         236            Cursos Livres Outros                                                               194             Cobrança indevida/abusiva                                                                                      entre 41 a 50 anos     65035620.0       1
                               2016-11-16 09:41:41.000  2016-02-16 09:53:34.000  3             Sudeste       SP  VIA VAREJO S/A                                         CASAS BAHIA/PONTO FRIO (LOJAS FÍSICAS)  1     3.304126e+13  33041260.0   VIA VAREJO S/A                                                       4753900.0      COMÉRCIO VAREJISTA ESPECIALIZADO DE ELETRODOMÉSTICOS E EQUIPAMENTOS DE ÁUDIO E VÍDEO                    S         122            Móveis Para Quarto                                                                 105             Produto com vício                                                                                              entre 21 a 30 anos     9843400.0        1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
N               2013           2013-11-25 11:53:44.000  2013-11-25 11:50:38.000  5             Centro-oeste  DF  BANCO DO BRASIL SA                                     DIRECAO GERAL                           1     1.910000e+02  0.0          BANCO DO BRASIL SA                                                   6422100.0      BANCOS MÚLTIPLOS, COM CARTEIRA COMERCIAL                                                                N         53             Banco comercial                                                                    230             Tarifas Bancárias – Cobrança não autorizada.                                                                   Nao Informada          70333900.0       1
                2015           2015-02-12 09:46:08.000  2015-01-15 09:28:48.000  3             Sudeste       ES  JONIL MATERIAL DE CONSTRUÇÃO LTDA                      JONIL MATERIAL DE CONSTRUÇÃO            1     3.635593e+13  36355931.0   JONIL MATERIAL DE CONSTRUCAO LTDA - ME                               4744005.0      COMÉRCIO VAREJISTA DE MATERIAIS DE CONSTRUÇÃO NÃO ESPECIFICADOS ANTERIORMENTE                           N         283            Estabelecimento comercial (supermercado, loja, padaria, locadora, frutaria, etc.)  187             Serviço em desacordo com norma/lei                                                                             Nao Informada          29146520.0       1
                               2015-04-16 11:33:25.000  2013-10-18 11:44:03.000  5             Centro-oeste  DF  BAR E RESTAURANTE 103 LTDA ME                          BAR E RESTAURANTE 103                   1     6.289757e+12  6289757.0    BAR E RESTAURANTE ESTACAO 103 LTDA                                   5611201.0      RESTAURANTES E SIMILARES                                                                                N         3              Restaurante / Fast Food ( Refeições / Sanduíches Servidos Pelo Local )             15              Publicidade enganosa                                                                                           Nao Informada          70333900.0       1
                               2015-04-16 11:34:51.000  2013-03-25 10:05:27.000  5             Centro-oeste  DF  LOJAS AMERICANAS S/A                                   LOJAS AMERICANAS S/A                    1     3.301456e+13  33014556.0   LOJAS AMERICANAS S.A.                                                4711302.0      COMÉRCIO VAREJISTA DE MERCADORIAS EM GERAL, COM PREDOMINÂNCIA DE PRODUTOS ALIMENTÍCIOS - SUPERMERCADOS  S         146            Aparelho DVD                                                                       103             Manual de Instrução (em língua estrangeira/falta de informação/informação incorreta)                           Nao Informada          70333900.0       1
                2016           2016-12-01 09:16:18.000  2015-02-27 10:26:27.000  4             Sul           SC  BV FINANCEIRA SA CREDITO FINANCIAMENTO E INVESTIMENTO  BV FINANCEIRA                           1     1.149953e+12  1149953.0    BV FINANCEIRA SA CREDITO FINANCIAMENTO E INVESTIMENTO                6436100.0      SOCIEDADES DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO - FINANCEIRAS                                       S         79             Seguro                                                                             27              Contrato (não cumprimento, alteração, transferencia, irregularidade, rescisão, etc.)                           Nao Informada          89120000.0       1
Length: 3469, dtype: int64

In [ ]:
manufacturerNameCol = df['Atendida']
groupsSum = manufacturerNameCol.value_counts()
x = groupsSum.index
y = groupsSum
 
plt.figure(figsize=(15, 8))
ax = plt.axes()
ax.set_facecolor('#e9eaeb')
plt.xticks(rotation=180)
plt.xlabel('Legenda', fontsize=13)
plt.ylabel('Indice', fontsize=13)
plt.title('QUANTIDADE DE CHAMADOS ATENDIDOS E NAO ATENDIDOS', fontweight='bold', fontsize=17)
plt.bar(x, y, color='#0e4bef')
plt.grid(axis='y')
 
plt.show()

In [ ]:
#FILTRO DOS CHAMADOS
df[['AnoCalendario', 'Regiao', 'UF', 'DescricaoAssunto', 'DescricaoProblema']].groupby([
    'AnoCalendario', 'Regiao', 'UF', 'DescricaoAssunto', 'DescricaoProblema']).count()

## MINERACAO DE TEXTO - ARRUMANDO!

In [ ]:
# elimina pontuação, caracteres especiais, digitos de um texto 
texto_limpo2 = re.sub('(\\d|\\W)+', ' ', texto)
print(texto_limpo2)


texto = texto.lower() # Transforma o texto inteiro em minusculo
texto 

# Retorna os tokens mais comuns 
cont_token = Counter(word_tokenize(texto))
print(cont_token.most_common(10))

print(vectorizer.vocabulary_) # Apresenta o volcabulário com a contagem