# Atividade - Inteligência artificial <br>
### <font color='red'> Concatenação de datasets <font>

# RA's 

<center > Alex Vinicius Souza do Nascimento - 920110872	<br>
Alexsandro dos Santos Silva	-       319200068	<br>
Evelyn Castro Maia e Souza -        3019200390 <br>
Filipe Queiroz de Abreu	-           919210778 <br>
Kaike Soares Silva	-               919209611	 <br>
Nailda Rodrigues Gonçalves	-       919203559 <br>
    </ceter>

In [1]:
import pandas as pd

In [46]:
datasets = {}

for item in range(0,5):
    datasets["df{}".format(item)] = pd.read_csv('Data/reclamacoes-fundamentadas-sindec-201{}.csv'.format(item + 2))

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (22) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
frames = []

for item in range (0,5):
    fra

In [42]:
frames = 
df_full = pd.concat(datasets['df0'], datasets['df1'])

C:\Users\FILIPE~1\AppData\Local\Temp/ipykernel_4256/1191249839.py:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  df_full = pd.concat(datasets['df0'], datasets['df1'])

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [45]:
datasets['df1']

,AnoCalendario,DataArquivamento,DataAbertura,CodigoRegiao,Regiao,UF,strRazaoSocial,strNomeFantasia,Tipo,NumeroCNPJ,...,CNAEPrincipal,DescCNAEPrincipal,Atendida,CodigoAssunto,DescricaoAssunto,CodigoProblema,DescricaoProblema,SexoConsumidor,FaixaEtariaConsumidor,CEPConsumidor
0,2013,2013-07-17 13:42:50.000,2013-06-27 10:41:31.000,3,Sudeste,MG,BOMSUCESSO,NaN,1,NaN,...,NaN,NaN,S,63,Financeira,217,Antecipação de Financiamento,F,entre 51 a 60 anos,35300038
1,2013,2013-01-16 09:31:19.000,2012-12-06 09:33:00.000,2,Nordeste,RN,LOJAS INSINUANTE,NaN,1,NaN,...,NaN,NaN,S,101,"Telefone ( Convencional, Celular, Interfone, E...",102,"Garantia (Abrangência, cobertura, etc.)",F,entre 41 a 50 anos,59617335
2,2013,2013-09-12 09:42:11.000,2013-06-03 08:20:01.000,2,Nordeste,PE,AVELLOZ,AVELLOZ,1,NaN,...,NaN,NaN,S,145,Motos,105,Produto com vício,F,entre 41 a 50 anos,55036830
3,2013,2013-08-14 09:00:34.000,2013-07-18 08:46:37.000,3,Sudeste,RJ,EDSON RIBEIRO GONÇALVES JUNIOR,MEU LIVRO MINHA VIDA,1,NaN,...,NaN,NaN,N,235,Curso de Línguas,192,Desistência do serviço (artigo 49 - descumprim...,M,entre 51 a 60 anos,25035520
4,2013,2013-06-28 11:52:58.000,2013-06-10 13:23:23.000,3,Sudeste,RJ,CENTRO UNIVERSITÁRIO PLÍNIO LEITE,UNIPLI,1,NaN,...,NaN,NaN,N,236,Cursos Livres Outros,184,Serviço não fornecido (entrega/instalação/não ...,F,até 20 anos,24425470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268091,2013,2013-10-30 15:25:16.000,2013-04-02 15:06:34.000,2,Nordeste,PE,SAMSUNG ELETRONICA DA AMAZONIA LTDA,NaN,1,2.802730e+11,...,4649402.0,COMÉRCIO ATACADISTA DE APARELHOS ELETRÔNICOS D...,S,101,"Telefone ( Convencional, Celular, Interfone, E...",105,Produto com vício,M,entre 31 a 40 anos,50751110.0
268092,2013,2013-04-12 16:39:10.000,2012-10-05 16:03:08.000,2,Nordeste,PE,SAMSUNG ELETRONICA DA AMAZONIA LTDA,NaN,1,2.802730e+11,...,4649402.0,COMÉRCIO ATACADISTA DE APARELHOS ELETRÔNICOS D...,S,101,"Telefone ( Convencional, Celular, Interfone, E...",107,Não entrega/demora na entrega do produto,M,entre 31 a 40 anos,52040083.0
268093,2013,2013-10-03 12:37:32.000,2013-07-18 10:31:10.000,2,Nordeste,PE,SAMSUNG ELETRONICA DA AMAZONIA LTDA,NaN,1,2.802730e+11,...,4649402.0,COMÉRCIO ATACADISTA DE APARELHOS ELETRÔNICOS D...,S,95,"Aparelho de Som ( Gravador, 3x1, CD )",113,Falta de peca de reposição,M,entre 41 a 50 anos,54762780.0
268094,2013,2013-11-01 12:51:05.000,2013-06-07 12:49:34.000,2,Nordeste,PE,SAMSUNG ELETRONICA DA AMAZONIA LTDA,NaN,1,2.802730e+11,...,4649402.0,COMÉRCIO ATACADISTA DE APARELHOS ELETRÔNICOS D...,S,101,"Telefone ( Convencional, Celular, Interfone, E...",102,"Garantia (Abrangência, cobertura, etc.)",M,Nao Informada,50710140.0
268095,2013,2013-12-12 18:03:10.000,2013-10-30 15:02:07.000,2,Nordeste,PE,SAMSUNG ELETRONICA DA AMAZONIA LTDA,NaN,1,2.802730e+11,...,4649402.0,COMÉRCIO ATACADISTA DE APARELHOS ELETRÔNICOS D...,S,105,"Artigo de Foto Imagem ( Filme, Ampliador, Lune...",105,Produto com vício,F,entre 31 a 40 anos,55355000.0